name: Build and Draft Windows Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build .NET Windows Project (${{ matrix.arch }})
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [win-x64, win-arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project for ${{ matrix.arch }}
        run: dotnet build --no-restore --configuration Release -r ${{ matrix.arch }}

      - name: Upload Build Artifacts (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.arch }}
          path: |
            **/bin/Release/${{ matrix.arch }}/*.dll
            **/bin/Release/${{ matrix.arch }}/*.exe
            **/bin/Release/${{ matrix.arch }}/*.pdb
