name: Build and Draft Windows Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build .NET Windows Project
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Adjust if using a preview version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --no-restore --configuration Release

      - name: List Output Directory
        run: |
          echo "Build output structure:"
          dir . /s

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/bin/Release/*/*.dll
            **/bin/Release/*/*.exe
            **/bin/Release/*/*.pdb
